export const fontFamilies: string[] = [
  // Sans-serif
  "Arial",
  "Helvetica",
  "Verdana",
  "Tahoma",
  "Trebuchet MS",
  "Gill Sans",
  "Segoe UI",
  "Candara",
  "Futura",
  "Calibri",
  "Lucida Grande",
  "Century Gothic",
  "Geneva",
  "Optima",
  "Lucida Sans",

  // Serif
  "Times New Roman",
  "Georgia",
  "Garamond",
  "Palatino",
  "Bookman",
  "Baskerville",
  "Didot",
  "Cambria",
  "Constantia",
  "Perpetua",

  // Monospace
  "Courier New",
  "Courier",
  "Lucida Console",
  "Monaco",
  "Consolas",
  "Andale Mono",

  // Display / Decorative
  "Impact",
  "Arial Black",
  "Copperplate",
  "Rockwell",
  "Franklin Gothic Medium",
  "Avant Garde",
  "Bodoni",
  "Papyrus",
  "Comic Sans MS",
  "Brush Script MT",

  // Other popular web fonts
  "Lobster",
  "Pacifico",
  "Raleway",
  "Open Sans",
  "Roboto",
  "Montserrat",
  "Oswald",
  "Merriweather",
  "Playfair Display",
  "Lato",
  "Nunito",
  "Poppins",
  "Quicksand",
  "Roboto Condensed",
  "Source Sans Pro",
  "Ubuntu",
  "Dancing Script",
];
