export const TAG_GET_USERS = "TAG_GET_USERS" as const;
export const TAG_GET_TEMPLATES_ADMIN = "TAG_GET_TEMPLATES_ADMIN" as const;
export const COMMUNITY_MEMES = "COMMUNITY_MEMES" as const;
export const TAG_MEME_INTERACTION_SUMMARY = "TAG_MEME_INTERACTIONS_SUMMARY" as const; 